@startuml
!define ACTOR class

actor User

participant Postman as "Postman"
participant System as System <<Container>>
participant MongoDB as "MongoDB"

activate User
User -> Postman: 1. Solicitação de lista de edifícios com Min/Max pisos
activate Postman

Postman -> System: 2. Requisição GET /buildings?minFloors=1&maxFloors=10
activate System

System -> System: 3. Verificação de autorização
System -> MongoDB: 4. Consulta ao banco de dados
activate MongoDB

MongoDB --> System: 5. Retorna lista de edifícios
System --> Postman: 6. Retorna lista de edifícios (JSON)
deactivate MongoDB

Postman --> User: 7. Exibe lista de edifícios (JSON)
deactivate Postman
deactivate System
deactivate User
@enduml
