@startuml
'https://plantuml.com/sequence-diagram

actor User as "Gestor de Campus"
participant SC as "<<System (C4)>> sSCS:SSCS"
activate User
User -> SC : Lista pidos de edífcio servidos por elevador
activate SC
SC-->User : Introduz Dados
deactivate SC
User -> SC : Dados do building Name
activate SC
SC --> User : Pisos de edíficio servidos por eleavdor Listados / erro nos dados



deactivate User
@enduml

