@startuml
!define ACTOR class

actor User

participant ElevatorRoute
participant IElevatorController
participant ElevatorController
participant IElevatorService
participant ElevatorService
participant ElevatorRepo
participant Elevator
participant IElevatorDTO

User -> ElevatorRoute: Solicitação para criar um elevador em um edifício (POST)
activate ElevatorRoute
ElevatorRoute -> IElevatorController: createElevator(elevator)
IElevatorController -> ElevatorController: createElevator(elevator)
activate ElevatorController
ElevatorController -> IElevatorService: createElevator(elevator)
activate IElevatorService
IElevatorService -> ElevatorService: createElevator(elevator)
activate ElevatorService
ElevatorService -> ElevatorRepo: createElevator(elevator)
activate ElevatorRepo
ElevatorRepo -> Elevator: create(elevator)
activate Elevator
Elevator -> ElevatorRepo: Elevador criado
deactivate Elevator
ElevatorRepo -> ElevatorService: Elevador criado
deactivate ElevatorRepo
ElevatorService -> IElevatorDTO: Elevador criado
activate IElevatorDTO
IElevatorDTO --> ElevatorService: Dados do Elevador
deactivate IElevatorDTO
ElevatorService --> ElevatorController: Dados do Elevador
deactivate ElevatorService
ElevatorController --> ElevatorRoute: Dados do Elevador
deactivate ElevatorController
ElevatorRoute --> User: 200 OK, JSON
deactivate ElevatorRoute
deactivate User
@enduml
