@startuml
'http://plantuml.com/skinparam.html

actor User
participant Postman as "Postman"
participant System as System <<Container>>
participant MongoDB as "MongoDB"

activate User
User -> Postman :1. Dar informação {builduingName, floors, position}
activate Postman
Postman -> System :2. POST updateElevator /{builduingName, floors, position}
activate System
System -> System :3. Check verification

System -> MongoDB :4. Save elevator
activate MongoDB
MongoDB -> System :5. Return elevator
deactivate MongoDB
System -> Postman :6. Return elevator (JSON)
deactivate System
Postman -> User :7. Show Elevator (JSON)
deactivate Postman
deactivate User


@enduml