@startuml
!define ACTOR class

actor User

participant ElevatorRoute
participant IElevatorController
participant ElevatorController
participant IElevatorService
participant ElevatorService
participant ElevatorRepo
participant Elevator
participant IElevatorDTO

User -> ElevatorRoute: List Elevators in Building
activate ElevatorRoute
ElevatorRoute -> IElevatorController : getElevatorsInBuilding()
activate IElevatorController
IElevatorController -> ElevatorController : getElevatorsInBuilding()
deactivate IElevatorController
activate ElevatorController
ElevatorController -> IElevatorService : getElevatorsInBuilding()
activate IElevatorService
IElevatorService -> ElevatorService : getElevatorsInBuilding()
deactivate IElevatorService
activate ElevatorService
ElevatorService -> ElevatorRepo : getElevatorsInBuilding()
activate ElevatorRepo
ElevatorRepo -> Elevator : findElevatorsInBuilding()
activate Elevator
Elevator -> ElevatorRepo : Elevators
deactivate Elevator
ElevatorRepo -> ElevatorService : Elevators
deactivate ElevatorRepo
ElevatorService -> IElevatorDTO : Elevators
activate IElevatorDTO
IElevatorDTO -> ElevatorService : ElevatorDTO
deactivate IElevatorDTO
ElevatorService -> ElevatorController : ElevatorDTO
deactivate ElevatorService
ElevatorController -> ElevatorRoute : res.json(ElevatorDTO).status()
deactivate ElevatorController
ElevatorRoute -> User
deactivate ElevatorRoute
@enduml
