@startuml
'http://plantuml.com/skinparam.html

actor User
participant Postman as "Postman"
participant System as "Container"
participant MongoDB as "MongoDB"

activate User
User -> Postman :1. Dar informação {name, description, depth, witdh}
activate Postman
Postman -> System :2. POST createBuilding /{name, description, depth, witdh}
activate System
System -> System :3. Check verification

System -> MongoDB :4. Save building
activate MongoDB
MongoDB -> System :5. Return building
deactivate MongoDB
System -> Postman :6. Return building (JSON)
deactivate System
Postman -> User :7. Show Building (JSON)
deactivate Postman
deactivate User


@enduml
```