@startuml
'https://plantuml.com/sequence-diagram

actor User as "Gestor de Campus"
participant SC as "<<System (C4)>> sSCS:SSCS"
activate User
User -> SC : Lista Elevadores em Edificio
activate SC
SC-->User : Introduz Dados
deactivate SC
User -> SC : Dados do building Name
activate SC
SC --> User : Elevadores em edificio Listados / erro nos dados



deactivate User
@enduml

