@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
participant Postman
participant System <<Container>>
participant MongoDB

activate User
User -> Postman : Dar informaçao {building1,building2,piso1,piso2}
activate Postman
Postman -> System : POST {building1,building2,piso1,piso2}
activate System
System -> System : check verifications
System -> MongoDB : Save passage
activate MongoDB
MongoDB --> System : Return passage
deactivate MongoDB
System --> Postman : Return passage (JSON)
deactivate System
Postman -> User : Show Passage (JSON)
deactivate Postman
deactivate User
@enduml