@startuml
'https://plantuml.com/sequence-diagram

actor User as "Gestor de Campus"
participant SC as "<<System (C4)>> sSCS:SSCS"
activate User
User -> SC : Editar Elevator
activate SC
SC-->User : Introduz Dados
deactivate SC
User -> SC : Dados do Elevator
activate SC
SC --> User : Elevator editado/ erro nos dados



deactivate User
@enduml

