@startuml
!define ACTOR class

actor User as "GestorDeCampus"
participant UI as "<<System>> UI"
participant MD as "<<System>> MD"
participant ElevatorRoute
participant IElevatorController
participant ElevatorController
participant IElevatorService
participant ElevatorService
participant ElevatorRepo
participant Elevator
participant IElevatorDTO

activate User
User -> UI: Edita um elevador existente (PUT)
activate UI
UI -> User: Introduz os novos dados do elevador
deactivate UI
User -> UI: envia os novos dados do elevador
activate UI
UI -> MD: Put /elevators dados
activate MD
MD -> ElevatorRoute: Put /elevators dados
deactivate MD
deactivate UI

activate ElevatorRoute
ElevatorRoute -> IElevatorController: updateElevator(elevator)
IElevatorController -> ElevatorController: updateElevator(elevator)
activate ElevatorController
ElevatorController -> IElevatorService: updateElevator(elevator)
activate IElevatorService
IElevatorService -> ElevatorService: updateElevator(elevator)
activate ElevatorService
ElevatorService -> ElevatorRepo: updateElevator(elevator)
activate ElevatorRepo
ElevatorRepo -> Elevator: update(elevator)
activate Elevator
Elevator -> ElevatorRepo: Elevador atualizado
deactivate Elevator
ElevatorRepo -> ElevatorService: Elevador atualizado
deactivate ElevatorRepo
ElevatorService -> IElevatorDTO: Dados do Elevador atualizado
activate IElevatorDTO
IElevatorDTO --> ElevatorService: Dados do Elevador
deactivate IElevatorDTO
ElevatorService --> ElevatorController: Dados do Elevador
deactivate ElevatorService
ElevatorController --> ElevatorRoute: Dados do Elevador
deactivate ElevatorController
ElevatorRoute --> MD: Dados do Elevador
deactivate ElevatorRoute
MD --> UI: 200 OK, JSON ou 400 Bad Request
activate UI
UI --> User: 200 OK, JSON ou 400 Bad Request
deactivate UI
deactivate User
@enduml
