@startuml
'https://plantuml.com/sequence-diagram

actor User
participant floorRoute
participant IFloorController
participant floorController
participant IFloorService
participant floorService
participant IFloorRepo
participant floorRepo
participant FloorMap
participant IFloorDTO

User -> floorRoute : GET /
activate floorRoute
floorRoute -> IFloorController : findFloorsWithPassagese()
activate IFloorController
IFloorController -> floorController : findFloorsWithPassages()
deactivate IFloorController
activate floorController
floorController -> IFloorService : findFloorsWithPassages()
activate IFloorService
IFloorService -> floorService : findFloorsWithPassages()
deactivate IFloorService
activate floorService
floorService -> IFloorRepo : findFloorsWithPassages()
activate IFloorRepo
IFloorRepo -> floorRepo : findFloorsWithPassages()
activate floorRepo
deactivate IFloorRepo
floorRepo --> floorService : floor[]
deactivate floorRepo
floorService -> FloorMap : toDTO()
activate FloorMap
FloorMap -> IFloorDTO
FloorMap --> floorService : floorDTO[]
deactivate FloorMap
floorService --> floorController: floorDTO[]
deactivate floorService
floorController --> floorRoute: floorController -> floorRoute : res.json(floorDTO).status()
deactivate floorController
floorRoute --> User
@enduml
