@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
participant SPA
participant MD <<Container>>
participant MongoDB

activate User
User->SPA : Carregar mapa de piso
activate SPA
SPA --> User : Pedido de dados
deactivate SPA
User -> SPA : Dar informaçao {id,map,passages:[{id,positionBuilding1,positionBuilding2}],elevator:{id,position},rooms:[{ id,position,distX,distY}]}
activate SPA

SPA -> MD : PATCH {id,map,passages:[{id,positionBuilding1,positionBuilding2}],elevator:{id,position},rooms:[{ id,position,distX,distY}]}
activate MD
MD -> MD : check verifications passages
MD -> MongoDB : Save passages
activate MongoDB
MongoDB --> MD : Return passages
deactivate MongoDB
MD -> MD : check verifications elevator
MD -> MongoDB : Save elevator
activate MongoDB
MongoDB --> MD : Return elevator
deactivate MongoDB
MD -> MD : check verifications rooms
MD -> MongoDB : Save rooms
activate MongoDB
MongoDB --> MD : Return rooms
deactivate MongoDB
MD -> MD : check verifications floor
MD -> MongoDB : Save floor
activate MongoDB
MongoDB --> MD : Return floor
deactivate MongoDB
MD --> SPA : status()
deactivate MD
SPA -> User : Confirmaçao/Erro
deactivate SPA
deactivate User
@enduml