@startuml
!define ACTOR class

actor User

participant ElevatorRoute
participant IElevatorController
participant ElevatorController
participant IElevatorService
participant ElevatorService
participant IElevatorRepo
participant ElevatorRepo
participant ElevatorMap
participant IElevatorPersistence
participant ElevatorSchema
participant Elevator
participant IElevatorDTO

User -> ElevatorRoute: Create Elevator
activate ElevatorRoute
ElevatorRoute -> IElevatorController : createElevator()
activate IElevatorController
IElevatorController -> ElevatorController : createElevator()
deactivate IElevatorController
activate ElevatorController
ElevatorController -> IElevatorService : createElevator()
activate IElevatorService
IElevatorService -> ElevatorService : createElevator()
deactivate IElevatorService
activate ElevatorService
ElevatorService -> Elevator : create()
activate Elevator
Elevator -> ElevatorService : Elevator
deactivate Elevator
ElevatorService -> IElevatorRepo: save()
activate IElevatorRepo
IElevatorRepo -> ElevatorRepo : save()
deactivate IElevatorRepo
activate ElevatorRepo
ElevatorRepo -> ElevatorMap : toPersistence()
activate ElevatorMap
activate IElevatorDTO
ElevatorMap -> IElevatorDTO : ElevatorData
IElevatorDTO -> ElevatorMap : ElevatorDTO
deactivate IElevatorDTO
deactivate ElevatorMap
IElevatorDTO -> ElevatorService : ElevatorDTO
ElevatorService -> ElevatorMap : ElevatorDTO
activate ElevatorMap
ElevatorMap -> IElevatorPersistence : savedElevatorData
IElevatorPersistence -> ElevatorSchema : save()
deactivate ElevatorMap
activate ElevatorSchema
ElevatorSchema -> IElevatorPersistence : savedElevatorData
IElevatorPersistence -> IElevatorRepo : savedElevatorData
deactivate ElevatorSchema
IElevatorRepo -> ElevatorRepo : savedElevatorData
deactivate IElevatorRepo
activate ElevatorRepo
ElevatorRepo -> ElevatorSchema: create()
activate ElevatorSchema
ElevatorSchema -> ElevatorRepo : NewElevatorData
deactivate ElevatorSchema
ElevatorRepo -> ElevatorService: savedElevatorData
ElevatorService -> ElevatorMap : toDTO()
activate ElevatorMap
ElevatorMap -> ElevatorService : savedElevatorDTO
deactivate ElevatorMap
ElevatorService -> ElevatorController : savedElevatorDTO
deactivate ElevatorService
ElevatorController -> ElevatorRoute : res.json(savedElevatorDTO).status()
deactivate ElevatorController
ElevatorRoute -> User
deactivate ElevatorRoute
@enduml
