@startuml
'http://plantuml.com/skinparam.html

actor User
participant Postman as "Postman"
participant System as "container"
participant MongoDB as "MongoDB"

activate User
User -> Postman :1. Dar informação {name}
activate Postman
Postman -> System :2. POST createRobotType /{name}
activate System
System -> System :3. Check verification

System -> MongoDB :4. Save RobotType
activate MongoDB
MongoDB -> System :5. Return RobotType
deactivate MongoDB
System -> Postman :6. Return RobotType (JSON)
deactivate System
Postman -> User :7. Show RobotType (JSON)
deactivate Postman
deactivate User


@enduml
```